# Generated by Django 6.0.3 on 2026-08-18 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('decision', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('approver_roles', models.CharField(blank=True, help_text='Roles held by the approver at the moment of the decision.', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='denial_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='granted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['user', '-created_at'], name='idx_file_access_user'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['granted', '-created_at'], name='idx_file_access_granted'),
        ),
        migrations.AddField(
            model_name='approvaldecisionlog',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_log', to='portal.approvalrequest'),
        ),
        migrations.AddField(
            model_name='approvaldecisionlog',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decision_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='approvaldecisionlog',
            index=models.Index(fields=['approval', '-created_at'], name='idx_approval_decision_log'),
        ),
    ]
