# Generated by Django 6.0.3 on 2026-08-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_public_recruitment_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationnode',
            name='currency',
            field=models.CharField(blank=True, help_text='ISO 4217 code, e.g. BDT or EUR. Blank inherits from the parent site.', max_length=3),
        ),
    ]
